name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - name: Installing dependencies
      run: sudo bash -c "curl -L https://dl.dpp.dev/latest -o /tmp/dpp.deb && apt update && apt install /tmp/dpp.deb libcurl4-openssl-dev libmpg123-dev libogg-dev libopus-dev libopusfile-dev libjsoncpp-dev -y && rm /tmp/dpp.deb"
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Release
      run: cd $GITHUB_WORKSPACE; RELEASE=$(grep -Po '(?<=VERSION )[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt); PROJECT=$(grep -Po '(?<=project\()[^\s\)]+' CMakeLists.txt); mv build/$PROJECT .; tar cvf "$PROJECT$RELEASE-linux-x64.tar.gz" LICENSE $PROJECT; gh release create $RELEASE "$PROJECT$RELEASE-linux-x64.tar.gz" || ( gh release delete $RELEASE -y; gh release create $RELEASE "$PROJECT$RELEASE-linux-x64.tar.gz")